---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-kafka
  namespace: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path  /var/log/flb-storage-kafka/
        storage.sync  normal
        storage.backlog.mem_limit 32MB
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output.conf
  output.conf: |
    [OUTPUT]
        Name                        kafka
        Match                       kube.var.log.containers.ngsa*.*
        brokers                     corp-monitoring-eh.servicebus.windows.net:9093
        topics                      test-for-ak
        rdkafka.security.protocol   SASL_SSL
        rdkafka.sasl.username       $ConnectionString
        rdkafka.sasl.password       ${EVENT_HUB_CONNECTION_STRING}
        rdkafka.sasl.mechanism      PLAIN
        storage.total_limit_size    15M
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/ngsa*.log
        Parser            cri
        DB                /var/log/flb_kube-kafka.db
        Mem_Buf_Limit     32MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
        storage.type      filesystem
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes_
    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        kubernetes_labels
        Add_prefix          kubernetes_labels_
    [FILTER]
        Name    modify
        Match   kube.*
        Add     Zone                                           ${ZONE}
        Add     Region                                         ${REGION}
        Copy    kubernetes_labels_app                          k_app
        Copy    kubernetes_container_name                      k_container
  parsers.conf: |
    [PARSER]
        Name         json
        Format       json
        Time_Key     time
        Time_Format  %d/%b/%Y:%H:%M:%S %z
        Time_Keep    Off
    [PARSER]
        Name         syslog
        Format       regex
        Regex        ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key     time
        Time_Format  %b %d %H:%M:%S
    [PARSER]
        Name         cri
        Format       regex
        Regex        ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    Off
