---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit-kafka
  namespace: fluentbit
  labels:
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/name: fluentbit-kafka
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit-kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fluentbit
        app.kubernetes.io/name: fluentbit-kafka
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: fluentbit
      terminationGracePeriodSeconds: 10
      containers:
        - name: fluentbit
          image: docker.io/fluent/fluent-bit:1.5
          imagePullPolicy: Always
          ports:
            - containerPort: 2020
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: EVENT_HUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: fluentbit-secrets
                  key: EventHubConnectionString
            - name: REGION
              value: eastus
            - name: ZONE
              value: az-eastus-dev
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluentbit-kafka
